// Import and register all your controllers from the importmap via controllers/**/*_controller
import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import FilterFormController from "./filter_form_controller"
import HelloController from "./hello_controller"
import ModalController from "./modal_controller"
import PasswordStrengthController from "./password_strength_controller"
import TomSelectController from "./tom_select_controller"
import AutoSubmitStatusController from "./auto_submit_status_controller"

application.register("filter-form", FilterFormController)
application.register("hello", HelloController)
application.register("modal", ModalController)
application.register("password-strength", PasswordStrengthController)
application.register("tom-select", TomSelectController)
application.register("auto-submit-status", AutoSubmitStatusController)
